# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_transferDialog(object):
    def setupUi(self, transferDialog):
        transferDialog.setObjectName("transferDialog")
        transferDialog.resize(278, 272)
        transferDialog.setMaximumSize(QtCore.QSize(278, 272))
        self.verticalLayout = QtWidgets.QVBoxLayout(transferDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.incomingTransferLabel = QtWidgets.QLabel(transferDialog)
        self.incomingTransferLabel.setObjectName("incomingTransferLabel")
        self.verticalLayout.addWidget(self.incomingTransferLabel)
        self.incomingTransferList = QtWidgets.QListWidget(transferDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incomingTransferList.sizePolicy().hasHeightForWidth())
        self.incomingTransferList.setSizePolicy(sizePolicy)
        self.incomingTransferList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.incomingTransferList.setObjectName("incomingTransferList")
        self.verticalLayout.addWidget(self.incomingTransferList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelBtn = QtWidgets.QPushButton(transferDialog)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.startBtn = QtWidgets.QPushButton(transferDialog)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(transferDialog)
        QtCore.QMetaObject.connectSlotsByName(transferDialog)

    def retranslateUi(self, transferDialog):
        _translate = QtCore.QCoreApplication.translate
        transferDialog.setWindowTitle(_translate("transferDialog", "Dialog"))
        self.incomingTransferLabel.setText(_translate("transferDialog", "Incoming Transfer"))
        self.cancelBtn.setText(_translate("transferDialog", "Cancel"))
        self.startBtn.setText(_translate("transferDialog", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    transferDialog = QtWidgets.QDialog()
    ui = Ui_transferDialog()
    ui.setupUi(transferDialog)
    transferDialog.show()
    sys.exit(app.exec_())
