# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.appIdLabel = QtWidgets.QLabel(self.centralwidget)
        self.appIdLabel.setObjectName("appIdLabel")
        self.gridLayout.addWidget(self.appIdLabel, 0, 0, 1, 1)
        self.appIdInput = QtWidgets.QLineEdit(self.centralwidget)
        self.appIdInput.setObjectName("appIdInput")
        self.gridLayout.addWidget(self.appIdInput, 0, 1, 1, 2)
        self.connectedDeviceLabel = QtWidgets.QLabel(self.centralwidget)
        self.connectedDeviceLabel.setObjectName("connectedDeviceLabel")
        self.gridLayout.addWidget(self.connectedDeviceLabel, 1, 0, 1, 1)
        self.coonectedDeviceDisplay = QtWidgets.QLineEdit(self.centralwidget)
        self.coonectedDeviceDisplay.setReadOnly(True)
        self.coonectedDeviceDisplay.setObjectName("coonectedDeviceDisplay")
        self.gridLayout.addWidget(self.coonectedDeviceDisplay, 1, 1, 1, 2)
        self.allowDiscoveryCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.allowDiscoveryCheckbox.setObjectName("allowDiscoveryCheckbox")
        self.gridLayout.addWidget(self.allowDiscoveryCheckbox, 2, 0, 1, 2)
        self.discoverBtn = QtWidgets.QPushButton(self.centralwidget)
        self.discoverBtn.setObjectName("discoverBtn")
        self.gridLayout.addWidget(self.discoverBtn, 2, 2, 1, 1)
        self.selectedFileListView = QtWidgets.QListView(self.centralwidget)
        self.selectedFileListView.setObjectName("selectedFileListView")
        self.gridLayout.addWidget(self.selectedFileListView, 3, 0, 1, 2)
        self.sendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBtn.setObjectName("sendBtn")
        self.gridLayout.addWidget(self.sendBtn, 3, 2, 1, 1)
        self.messageDisplay = QtWidgets.QTextEdit(self.centralwidget)
        self.messageDisplay.setObjectName("messageDisplay")
        self.gridLayout.addWidget(self.messageDisplay, 4, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appIdLabel.setText(_translate("MainWindow", "App Id"))
        self.connectedDeviceLabel.setText(_translate("MainWindow", "Connected Device"))
        self.allowDiscoveryCheckbox.setText(_translate("MainWindow", "Allow Discovery"))
        self.discoverBtn.setText(_translate("MainWindow", "Discover"))
        self.sendBtn.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
