# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.discoverBtn = QtWidgets.QPushButton(self.centralwidget)
        self.discoverBtn.setObjectName("discoverBtn")
        self.gridLayout.addWidget(self.discoverBtn, 4, 2, 1, 1)
        self.messageDisplay = QtWidgets.QTextEdit(self.centralwidget)
        self.messageDisplay.setObjectName("messageDisplay")
        self.gridLayout.addWidget(self.messageDisplay, 7, 0, 1, 3)
        self.appIdInput = QtWidgets.QLineEdit(self.centralwidget)
        self.appIdInput.setObjectName("appIdInput")
        self.gridLayout.addWidget(self.appIdInput, 0, 1, 1, 2)
        self.coonnectedIPLabel = QtWidgets.QLabel(self.centralwidget)
        self.coonnectedIPLabel.setObjectName("coonnectedIPLabel")
        self.gridLayout.addWidget(self.coonnectedIPLabel, 3, 0, 1, 1)
        self.sendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBtn.setObjectName("sendBtn")
        self.gridLayout.addWidget(self.sendBtn, 5, 2, 1, 1)
        self.transferProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.transferProgressBar.setProperty("value", 24)
        self.transferProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.transferProgressBar.setTextVisible(True)
        self.transferProgressBar.setInvertedAppearance(False)
        self.transferProgressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.transferProgressBar.setObjectName("transferProgressBar")
        self.gridLayout.addWidget(self.transferProgressBar, 6, 0, 1, 3)
        self.connectedDeviceLabel = QtWidgets.QLabel(self.centralwidget)
        self.connectedDeviceLabel.setObjectName("connectedDeviceLabel")
        self.gridLayout.addWidget(self.connectedDeviceLabel, 1, 0, 1, 1)
        self.selectedFileListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.selectedFileListWidget.setObjectName("selectedFileListWidget")
        self.gridLayout.addWidget(self.selectedFileListWidget, 5, 0, 1, 2)
        self.appIdLabel = QtWidgets.QLabel(self.centralwidget)
        self.appIdLabel.setObjectName("appIdLabel")
        self.gridLayout.addWidget(self.appIdLabel, 0, 0, 1, 1)
        self.coonectedDeviceDisplay = QtWidgets.QLineEdit(self.centralwidget)
        self.coonectedDeviceDisplay.setReadOnly(True)
        self.coonectedDeviceDisplay.setObjectName("coonectedDeviceDisplay")
        self.gridLayout.addWidget(self.coonectedDeviceDisplay, 1, 1, 1, 2)
        self.coonectedIPInput = QtWidgets.QLineEdit(self.centralwidget)
        self.coonectedIPInput.setAutoFillBackground(False)
        self.coonectedIPInput.setClearButtonEnabled(False)
        self.coonectedIPInput.setObjectName("coonectedIPInput")
        self.gridLayout.addWidget(self.coonectedIPInput, 3, 1, 1, 2)
        self.allowDiscoveryCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.allowDiscoveryCheckbox.setObjectName("allowDiscoveryCheckbox")
        self.gridLayout.addWidget(self.allowDiscoveryCheckbox, 4, 0, 1, 1)
        self.autoCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.autoCheckBox.setChecked(True)
        self.autoCheckBox.setObjectName("autoCheckBox")
        self.gridLayout.addWidget(self.autoCheckBox, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.discoverBtn.setText(_translate("MainWindow", "Discover"))
        self.coonnectedIPLabel.setText(_translate("MainWindow", "Coonected IP"))
        self.sendBtn.setText(_translate("MainWindow", "Send"))
        self.connectedDeviceLabel.setText(_translate("MainWindow", "Connected Device"))
        self.appIdLabel.setText(_translate("MainWindow", "App Id"))
        self.allowDiscoveryCheckbox.setText(_translate("MainWindow", "Allow Discovery"))
        self.autoCheckBox.setText(_translate("MainWindow", "Auto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
